# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76923b40edc211811adcfd623cc99de7856a03b899c0cfa551b94ae65f7a48dfa650d60f55d99a9e3ea9c93711beefd1b7d6818c04788d5a7ba6de2e6821238b

test:
  secret_key_base: 4b96afe678d93e22af027564cdaa5335b29fe01ff6c6b00a2b54f34e64d4552745211924cff1044f7205add167f1133f30ac258a2aebc5a7f8537d4106ca864c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
